### ISSUE TITLE
DS Reputation Checklist

### ISSUE THREAD

**Issue by nnamon** [nnamon/Zilliqa#1]
- [x] Add two constants: DS_PERFORMANCE_THRESHOLD_PERCENT, NUM_DS_BYZANTINE_REMOVED.
- [x] Measure performance of a DS Node by checking the Coinbase at the Vacuous epoch.
- [x] Produce a list of PoW Winners and Losers from the Performances during DS Block Preparation.
- [x] Validate the list of PoW Winners and Losers by backup DS Nodes.
- [x] Update DS Compositions from DS Block for both DS and other nodes.
- [x] Handle the consequences of aging/removed DS nodes.
